###get all blogs
GET http://localhost:3003/api/blogs
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1dSIsImlkIjoiNjBlNDQzMjliZDg5ZTcwZjk0MWFjMTU4IiwiaWF0IjoxNjI1NjQ1MDE2fQ.5KA8Y_KnmJT8MFoRg8DTUxDcmV1GrvTS_yNScg4Tu2c

###add new blog with token
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1dSIsImlkIjoiNjBlNDQzMjliZDg5ZTcwZjk0MWFjMTU4IiwiaWF0IjoxNjI1ODE3Mjk0fQ.oEth_mMqYv5afZEoRWQytT_xowPU8chpuMSZD4fB_rQ

{
  "title": "The first post",
  "author": "Luu",
  "url": "123",
}

###add new blog without token
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "React patterns",
  "author": "Michael Chan",
  "url": "https://reactpatterns.com/",
  "likes": 7
}

###update a blog
PUT http://localhost:3003/api/blogs/60e9517f48f9c4045fbf41bc
Content-Type: application/json

{
  "likes": 1280
}

###delete a blog using id
DELETE http://localhost:3003/api/blogs/60e4897a10b0b308121337d7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imx1dSIsImlkIjoiNjBlNDQzMjliZDg5ZTcwZjk0MWFjMTU4IiwiaWF0IjoxNjI1NjQ1MDE2fQ.5KA8Y_KnmJT8MFoRg8DTUxDcmV1GrvTS_yNScg4Tu2c
