###get all blogs
GET http://localhost:3003/api/blogs

###add new blog
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Hooked",
  "author": "Nir Eyal",
  "url": "https://www.nirandfar.com/hooked/",
  "likes": 1269
}